### ISSUE TITLE
Avoid downloading database if not needed

### ISSUE THREAD

**Issue by vincentbernat** [ipinfo/docker#6]
Hey!

I was thinking doing this:

```sh
#!/bin/sh

trap exit TERM

while true; do
    for DATABASE in ${IPINFO_DATABASES}; do
        RESPONSE=$(curl \
            --silent \
            --write-out '%{http_code}' \
            --remote-time \
            --location \
            --output "${DATABASE}.mmdb.new" \
            --time-cond "${DATABASE}.mmdb" \
            "https://ipinfo.io/data/free/${DATABASE}.mmdb?token=${IPINFO_TOKEN}")
        case "$RESPONSE" in
            200)
                echo "${DATABASE}.mmdb database downloaded in /data volume."
                mv "${DATABASE}.mmdb.new" "${DATABASE}.mmdb"
                ;;
            304)
                echo "${DATABASE}.mmdb database not modified."
                ;;
            *)
                echo "Failed to download ${DATABASE}.mmdb database (HTTP error $RESPONSE)."
                rm "${DATABASE}.mmdb.new" 2> /dev/null
                ;;
        esac
    done

    sleep "$UPDATE_FREQUENCY" &
    wait $!
done
```

(the `wait $!` is unrelated, it's to be able to kill the container easily, I'll submit a separate PR)

This avoids downloading the database when no modification. Question: when the API returns 304, does it count against the daily quota for the token?

**Comment by abdullahdevrel** [comment]
Hey @vincentbernat. It is great to hear from you. I am very happy to see you reviewing our OSS code. Thank you very much! Really appreciate it.

> when the API returns 304, does it count against the daily quota for the token?

Yes. From our software engineer:

> For Data Downloads, when we receive a request (e.g: `/data/example.mmdb`) we generate a signed Google Cloud Storage URL + count the Data Download at the same time and then we redirect to the signed Google Cloud Storage URL which is responsible for handling the download which determines the status code. So, because all requests to the `/data/example.mmdb` endpoint return a redirect, they all count as a Data Download request even if the download from Google Cloud Storage does not complete for some reason (e.g: the user cancels it, Google Cloud Storage returns a 304).
>
> If a user wants to avoid performing more downloads than necessary, they should use the checksums endpoint and compare the checksum of the local file which you wrote about in: https://community.ipinfo.io/t/using-checksums-to-find-data-downloads-updates/2555.

**Comment by vincentbernat** [comment]
Ack. See #8.
